### ISSUE TITLE
Exibir data/hora do deadline de eventos finalizados

### ISSUE THREAD

**Issue by reebr** [reebr/challenge-stats#1]
Sugerido pelo @matheusalbino no [discord][1]:

>  Quando um projeto passa a data limite de entrega(deadline), exiba a data do encerramento, ao invés de mostrar 1 mês atras por exemplo. Até pq a pessoa vai poder saber exatamente quando ocorreu o desafio.

A ideia é alterar o componente [`Challenge`][2] inserindo uma condicional (uma propriedade computada talvez?!) que verifique se a data atual já ultrapassou o deadline e, renderize:

| Texto | Quando |
| :---: | :---:  | 
|  **deadline**: em x dias | a data/hora atual for inferior ao deadline |
| finalizado em xx/xx/xxxx xx:xx:xx | a data/hora atual for superior/igual ao deadline |

[1]:https://discordapp.com/channels/573655082156032001/587796527393669142/628962718841438229
[2]:https://github.com/reebr/challenge-stats/blob/master/src/components/challenge/Challenge.vue#L8-L10

**Comment by matheusalbino** [comment]
@reebr seria esse caso mesmo.

- Cabe analisar se é necessário ou vale a pena exibir a hora juntamente com a data.
- Talvez não seja necessário substituir `deadline` por `finalizado`.

Exemplo:

Texto | Quando
-- | --
**deadline**: em x dias | a data/hora atual for inferior ao deadline
**deadline**: xx/xx/xxxx xx:xx:xx | a data/hora atual for superior/igual ao deadline

**Comment by reebr** [comment]
@matheusalbino é tranquilo colocar o horário, ele está disponível no [arquivo de configuração](https://github.com/reebr/challenge-stats/blob/master/src/challenges.json#L7). Como o @codigofalado sempre define uma hora final pra fechar as PRs, eu coloquei esse dado no arquivo também.

Acho que não precisa dos segundos, só `DD/MM/YYYY HH:mm`. O que acha?

**Comment by matheusalbino** [comment]
@reebr yep! acho que não precisa dos segundos.
